project_id = "doulsumepjfihqowzheq"

[functions.send-login-email]
verify_jwt = false

[functions.workable-importer-complete]
verify_jwt = false

[functions.workable-integration-enhanced]
verify_jwt = false

[functions.workable-candidates]
verify_jwt = false

[functions.workable-jobs]
verify_jwt = false

[functions.update-user-password]
verify_jwt = false